name: socale
description: Discover And Build Your College Network.

publish_to: "none"

version: 0.2.2+6

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  #Flutter libraries
  flutter:
    sdk: flutter

  # Amplify libraries
  amplify_flutter: 1.0.0-next.1+1
  amplify_auth_cognito: 1.0.0-next.1

  # Firebase libraries
  firebase_core: 2.3.0
  firebase_messaging: 14.1.2

  # Local notifications libraries
  flutter_local_notifications: 12.0.3

  # Riverpod libraries
  flutter_riverpod: 2.1.1

  # Local database libraries
  isar: 3.0.2
  isar_flutter_libs: 3.0.2
  shared_preferences: 2.0.15

  # UI libraries
  flutter_svg: 1.1.5
  animations: 2.0.7
  simple_shadow: 0.3.0
  google_fonts: 3.0.1

  # Service libraries
  url_launcher: ^6.1.6
  pin_code_fields: ^7.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  isar_generator: 3.0.2
  build_runner: 2.1.11


flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/get_started/
    - assets/forgot_password/
    - assets/verify_email/
    - google_fonts/
