name: socale
description: Discover And Build Your College Network.

publish_to: "none"

version: 0.2.2+6

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  #Flutter sdk
  flutter:
    sdk: flutter

  http: ^0.13.5

  rive: ^0.10.2

  # Amplify libraries
  amplify_flutter: ^1.0.0-next.6
  amplify_auth_cognito: ^1.0.0-next.6

  # Firebase libraries
  firebase_core: ^2.7.1
  firebase_messaging: ^14.2.6

  # Local notifications libraries
  flutter_local_notifications: ^13.0.0

  # Riverpod libraries
  flutter_riverpod: ^2.3.0

  # Local database libraries
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  shared_preferences: ^2.0.18

  # UI libraries
  flutter_svg: ^2.0.2
  animations: ^2.0.7
  simple_shadow: ^0.3.1
  google_fonts: ^4.0.3

  # Service libraries
  url_launcher: ^6.1.10
  pin_code_fields: ^7.4.0
  intl: ^0.18.0

  flutter_native_splash: ^2.2.19
  flextras: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/illustrations/
    - assets/background/
    - assets/animations/icons/
    - assets/fonts/poppins/
    - assets/fonts/roboto/

