name: socale
description: A new kind of social network

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
