name: socale
description: Discover And Build Your College Network.

publish_to: "none"

version: 0.2.2+6

environment:
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies:
  #Flutter sdk
  flutter:
    sdk: flutter

  http: ^0.13.5

  rive: ^0.10.3

  # Amplify libraries
  amplify_flutter: ^1.0.0-next.7
  amplify_auth_cognito: ^1.0.0-next.7

  # Firebase libraries
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0

  # Local notifications libraries
  flutter_local_notifications: ^13.0.0

  # Riverpod libraries
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2

  # Local database libraries
  shared_preferences: ^2.0.20

  # UI libraries
  flutter_svg: ^2.0.4
  animations: ^2.0.7
  simple_shadow: ^0.3.1
  google_fonts: ^4.0.3

  # Service libraries
  url_launcher: ^6.1.10
  pin_code_fields: ^7.4.0
  intl: ^0.18.0

  flutter_native_splash: ^2.2.19
  flextras: ^1.0.0

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dio: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  riverpod_generator: ^2.1.4
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/illustrations/
    - assets/background/
    - assets/animations/icons/
    - assets/fonts/poppins/
    - assets/fonts/roboto/

