name: socale
description: Discover And Build Your College Network.

publish_to: "none"

version: 0.2.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_flutter: 0.6.10
  amplify_auth_cognito: 0.6.10

  firebase_core_platform_interface: 4.0.1
  firebase_core: 1.8.0
  firebase_messaging: 10.0.9

  cupertino_icons: 1.0.2
  flutter_svg: 1.1.5
  aws_signature_v4: 0.1.2
  animations: 2.0.7
  flutter_riverpod: 2.1.1
  isar: 3.0.2
  isar_flutter_libs: 3.0.2
  google_fonts: 3.0.1
  shared_preferences: 2.0.15
  flutter_local_notifications: 12.0.3
  simple_shadow: 0.3.0
  inner_shadow_widget: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  isar_generator: 3.0.2
  build_runner: 2.1.11


flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/get_started/
    - google_fonts/
