name: socale
description: A new kind of social network

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_riverpod: ^2.0.0-dev.9
  aws_signature_v4: ^0.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  amplify_analytics_pinpoint: ^0.6.1
  amplify_api: ^0.6.1
  amplify_auth_cognito: ^0.6.1
  amplify_datastore: ^0.6.1
  amplify_flutter: ^0.6.5
  amplify_storage_s3: ^0.6.1
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.2
  flappy_search_bar_ns: ^2.0.2
  flutter_svg: ^1.1.1+1
  get: ^4.6.1
  get_it: ^7.2.0
  glassmorphism: ^3.0.0
  google_fonts: ^2.3.1
  image_picker: ^0.8.4+11
  infinite_scroll_pagination: ^3.1.0
  injectable: ^1.5.3
  pin_code_fields: ^7.4.0
  simple_gradient_text: ^1.2.2
  flutter_image_compress: ^1.1.0
  path_provider: ^2.0.11
  aws_common: ^0.1.1
  flutter_dotenv: ^5.0.2
  webcrypto: ^0.5.2
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  animations: ^2.0.3
  colorful_safe_area: ^0.3.0
  provider: ^6.0.3
  flutter_chat_ui: ^1.5.8
  file_picker: ^4.6.1
  open_file: ^3.2.1

dev_dependencies:
  flutter_lints: ^1.0.0
  hive_generator:
  injectable_generator:
  build_runner:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
