enum OnboardingStep {
  schoolEmailVerification,
  started,
  bio,
  collegeInfo,
  skills,
  academicInterests,
  careerGoals,
  selfDescription,
  leisureInterests,
  idealFriendDescription,
  situationalDecisions,
  avatar,
  completed,
}
