enum OnboardingStep {
  started,
  academicInclination,
  biographics,
  collegeInfo,
  academicInterests,
  skills,
  careerGoals,
  selfDescription,
  leisureInterests,
  idealFriendDescription,
  situationalDecisions,
  avatarSelection,
  completed,
}
