enum OnboardingStep {
  schoolEmailVerification,
  started,
  bio,
  collegeInfo,
  academicInterests,
  skills,
  careerGoals,
  selfDescription,
  leisureInterests,
  idealFriendDescription,
  situationalDecisions,
  avatarSelection,
  completed,
}
