// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw82A-CgWn3nHlFs8NSDdFzwn5nVvpCp4',
    appId: '1:575550339662:android:ef1fbc9842fd040f7d611f',
    messagingSenderId: '575550339662',
    projectId: 'socale-cea9d',
    storageBucket: 'socale-cea9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIsgMQolUkbeKtY0W-KFXCyDzKyeAB0H4',
    appId: '1:575550339662:ios:270490ca51d1c0a27d611f',
    messagingSenderId: '575550339662',
    projectId: 'socale-cea9d',
    storageBucket: 'socale-cea9d.appspot.com',
    androidClientId: '575550339662-6u9opcljbltn36clnt6d48soahiar86l.apps.googleusercontent.com',
    iosClientId: '575550339662-u1l3knousnhms27ccfnmrq0d937nkaph.apps.googleusercontent.com',
    iosBundleId: 'co.socale.socale',
  );
}
