final Map<String, List<String>> hobbiesOptionsList = {
  '🪂 Adventure': ['Paragliding', 'Rafting', 'Scuba Diving', 'Skydiving', 'Theme Parks'],
  '🦄 Animals': [],
  '🏎️ Cars': [],
  '🎨 Creative': [
    'Animation',
    'Crochet & Sewing',
    'Drawing',
    'Graphic Design',
    'Music',
    'Painting',
    'Photography',
    'Videography'
  ],
  '✈️ Exploration': ['Exploring', 'Traveling'],
  '👜 Fashion': [
    'Avant-garde',
    'Chic',
    'DIY',
    'Grunge',
    'High-end/Designer',
    'Minimalism',
    'Skatecore',
    'Streetwear',
    'Techwear/Gorpcore',
    'Vintage/Workwear',
    'Y2K/Cyber'
  ],
  '🍟 Food': ['Boba', 'Cooking'],
  '🎲 Games': ['Board Games', 'Bowling', 'Chess', 'Computer Games', 'Gambling', 'Puzzles'],
  '💪 Gym': [],
  '💡 Learning': ['Journaling', 'Networking', 'Podcasts', 'Reading', 'Storywriting'],
  '🍿 Movies & Shows': [
    'Action',
    'Anime',
    'Comedy',
    'Crime/Thriller',
    'Documentaries',
    'Drama',
    'Horror',
    'K-Drama',
    'Musicals',
    'Noir',
    'Psychological',
    'Romance',
    'Sci-Fi'
  ],
  '🎧 Music': [
    'Alt/Indie',
    'Blues',
    'Classical',
    'Country',
    'Dance/Electronic',
    'Experimental',
    'Folk',
    'Hip-hop/Rap',
    'Jazz',
    'K-Pop',
    'Metal',
    'Pop',
    'R&B',
    'Rock'
  ],
  '🌳 Outdoors': [
    'Beach Outs',
    'Biking',
    'Camping',
    'Climbing',
    'Fishing',
    'Gardening',
    'Hiking',
    'Stargazing'
  ],
  '🎍 Self Care': ['Meditation', 'Skincare', 'Yoga'],
  '🍻 Socializing': ['Drinking', 'Going out with Friends', 'Partying & Clubbing', 'Smoking'],
  '⛳ Sports': [
    'Archery',
    'Badminton',
    'Baseball',
    'Basketball',
    'Biking',
    'Cricket',
    'Cricket',
    'Fencing',
    'Field hockey',
    'Football',
    'Football',
    'Formula 1',
    'Freestyle',
    'Golf',
    'Ice Hockey',
    'Martial Arts',
    'Skating',
    'Snowboarding',
    'Soccer',
    'Swimming',
    'Tennis',
    'Track',
    'Volleyball'
  ],
  '🕹️ Video Games': [
    'Apex',
    'Battlefield',
    'CS:GO',
    'Call of Duty',
    'Fallout',
    'Fortnite',
    'Halo',
    'League of Legends',
    'Minecraft',
    'Nintendo Games',
    'Overwatch',
    'Racing',
    'Rocket League',
    'Skyrim',
    'Smash Bros / Smash Ultimate',
    'Valorant'
  ]
};
