final Map<String, List<String>> hobbiesOptionsList = {
  '🌳 Outdoors': [
    'Hiking',
    'Climbing',
    'Fishing',
    'Stargazing',
    'Camping',
    'Beach Outs',
    'Biking',
    'Gardening'
  ],
  '✈️ Exploration': ['Traveling', 'Exploring'],
  '🍟 Food': ['Boba', 'Cooking'],
  '🍻 Socializing': [
    'Partying & Clubbing',
    'Drinking',
    'Smoking',
    'Going out with Friends'
  ],
  '💪 Gym': [],
  '⛳ Sports': [
    'Fencing',
    'Golf',
    'Martial Arts',
    'Archery',
    'Formula 1',
    'Skating',
    'Snowboarding',
    'Freestyle',
    'Basketball',
    'Soccer',
    'Volleyball',
    'Football',
    'Cricket',
    'Baseball',
    'Field hockey',
    'Ice Hockey',
    'Biking',
    'Swimming',
    'Track',
    'Cricket',
    'Tennis',
    'Badminton',
    'Football'
  ],
  '🎍 Self Care': ['Yoga', 'Meditation', 'Skincare'],
  '🎲 Games': [
    'Bowling',
    'Chess',
    'Board Games',
    'Gambling',
    'Puzzles',
    'Computer Games'
  ],
  '🍿 Movies & Shows': [
    'Action',
    'Drama',
    'Comedy',
    'Romance',
    'K-Drama',
    'Anime',
    'Documentaries',
    'Horror',
    'Sci-Fi',
    'Crime/Thriller',
    'Musicals',
    'Noir',
    'Psychological'
  ],
  '🎧 Music': [
    'Hip-hop/Rap',
    'Rock',
    'Alt/Indie',
    'K-Pop',
    'Pop',
    'Dance/Electronic',
    'Experimental',
    'Classical',
    'Country',
    'Metal',
    'Jazz',
    'R&B',
    'Blues',
    'Folk'
  ],
  '👜 Fashion': [
    'Streetwear',
    'Vintage/Workwear',
    'High-end/Designer',
    'Avant-garde',
    'Techwear/Gorpcore',
    'Minimalism',
    'Y2K/Cyber',
    'Grunge',
    'Skatecore',
    'DIY',
    'Chic'
  ],
  '🪂 Adventure': [
    'Skydiving',
    'Rafting',
    'Scuba Diving',
    'Paragliding',
    'Theme Parks'
  ],
  '💡 Learning': [
    'Reading',
    'Podcasts',
    'Networking',
    'Journaling',
    'Storywriting'
  ],
  '🎨 Creative': [
    'Animation',
    'Photography',
    'Videography',
    'Graphic Design',
    'Drawing',
    'Crochet & Sewing',
    'Painting',
    'Music'
  ],
  '🏎️ Cars': [],
  '🦄 Animals': [],
  '🕹️ Video Games': [
    'League of Legends',
    'Smash Bros / Smash Ultimate',
    'Minecraft',
    'Nintendo Games',
    'Rocket League',
    'Racing',
    'Valorant',
    'Fortnite',
    'Overwatch',
    'Call of Duty',
    'Battlefield',
    'Halo',
    'Apex',
    'CS:GO',
    'Fallout',
    'Skyrim'
  ]
};
