final List<String> majorsMinorOptionsList = [
  'African American Studies',
  'Anthropology',
  'Bio-Engineering',
  'Biological Sciences',
  'Chemistry & Biochemistry',
  'Chinese Studies',
  'Cognitive Science',
  'Communication',
  'Computer Science',
  'Data Science',
  'Economics',
  'Education Studies',
  'Electrical & Computer Eng',
  'Environmental Studies',
  'Ethnic Studies',
  'Gender Studies',
  'Global Health',
  'Global South Studies',
  'History',
  'Human Development Sciences',
  'International Studies',
  'Japanese Studies',
  'Jewish Studies',
  'Latin American Studies',
  'Linguistics',
  'Literature',
  'Mathematics',
  'Mechanical Engineering',
  'Music',
  'Nano Engineering',
  'Philosophy',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Health',
  'Rady School of Management',
  'Religion',
  'Scripps Institute',
  'Sociology',
  'Structural Engineering',
  'Theatre',
  'Urban Studies',
  'Visual Arts'
];
