final List<String> majorsMinorOptionsList = [
  'African American Studies',
  'Anthropology',
  'Bio-Engineering',
  'Biological Sciences',
  'Chemistry & Biochemistry',
  'Chinese Studies',
  'Cognitive Science',
  'Communication',
  'Computer Science',
  'Data Science',
  'Electrical & Computer Eng',
  'Economics',
  'Education Studies',
  'Environmental Studies',
  'Ethnic Studies',
  'Gender Studies',
  'Global Health',
  'Global South Studies',
  'Human Development Sciences',
  'History',
  'International Studies',
  'Japanese Studies',
  'Jewish Studies',
  'Latin American Studies',
  'Linguistics',
  'Literature',
  'Mechanical Engineering',
  'Mathematics',
  'Music',
  'Nano Engineering',
  'Philosophy',
  'Physics',
  'Political Science',
  'Public Health',
  'Psychology',
  'Rady School of Management',
  'Religion',
  'Scripps Institute',
  'Sociology',
  'Structural Engineering',
  'Theatre',
  'Urban Studies',
  'Visual Arts'
];
