const List<String> ucsdMajors = [
  'Anthropology',
  'Archaeology',
  'Biological Anthropology',
  'Sociocultural Anthropology',
  'Anthropology w/ Climate Change & Human Solutions',
  'Bioengineering',
  'Biotechnology',
  'Bioinformatics',
  'BioSystems',
  'Biology w/ Bioinformatics',
  'Ecology, Behavior & Evolution',
  'General Biology',
  'Human Biology',
  'Microbiology',
  'Molecular & Cell Biology',
  'Neurobiology',
  'Biochemistry & Cell Biology',
  'Physiology & Neuroscience',
  'Molecular Biology',
  'Black Diaspora & African American Studies',
  'Biochemistry',
  'Chemistry',
  'Environmental Chemistry',
  'Molecular Synthesis',
  'Pharmacological Chemistry',
  'Chinese Studies',
  'Classical Studies',
  'Cognitive Science w/ Clinical Aspects of Cognition',
  'Cognitive Science w/ Design & Interaction',
  'Cognitive Science w/ Language & Culture',
  'Cognitive Science w/ Machine Learning & Neural Computation',
  'Cognitive Science w/ Neuroscience',
  'Cognitive & Behavioral Neuroscience',
  'Communication',
  'Computer Engineering',
  'Computer Science',
  'Computer Science w/ Bioinformatics',
  'Critical Gender Studies',
  'Data Science',
  'Business Economics',
  'Economics',
  'Economics & Mathematics',
  'Public Policy',
  'Education Sciences',
  'Electrical Engineering',
  'Electrical Engineering & Society',
  'Engineering Physics',
  'Earth Sciences',
  'Environmental Policy',
  'Ethnic Studies',
  'German Studies',
  'Global Health',
  'Global South Studies',
  'Public Health',
  'Public Health w/ Biostatistics',
  'Public Health w/ Climate & Environmental Sciences',
  'Public Health w/ Community Health Sciences',
  'Public Health w/ Epidemiology',
  'Public Health w/ Health Policy & Management Sciences',
  'Public Health w/ Medicine Sciences',
  'History',
  'Human Developmental Sciences',
  'Human Developmental Sciences w/ Equity & Diversity',
  'Human Developmental Sciences w/ Healthy Aging',
  'International Studies in Anthropology',
  'International Studies in Economics',
  'International Studies in History',
  'International Studies in International Business',
  'International Studies in Linguistics',
  'International Studies in Literature',
  'International Studies in Philosophy',
  'International Studies in Political Science',
  'International Studies in Sociology',
  'Italian Studies',
  'Japanese Studies',
  'Jewish Studies',
  'Latin American Studies',
  'Latin American Studies w/ Mexico',
  'Latin American Studies w/ Migration & Border Studies',
  'Linguistics',
  'Linguistics w/ Cognition & Language',
  'Linguistics w/ Language & Society',
  'Language Studies w/ Individual Language',
  'Linguistics w/ Speech & Language Sciences',
  'Literatures in English',
  'Spanish Literature',
  'Literature/Writing',
  'World Literature & Culture',
  'Applied Mathematics',
  'Mathematics',
  'Mathematics & Applied Science',
  'Mathematics & Computer Science',
  'Mathematics & Secondary Education',
  'Probability & Statistics',
  'Aerospace Engineering',
  'Mechanical Engineering',
  'Mechanical Engineering w/ Controls & Robotics',
  'Mechanical Engineering w/ Fluid Mechanics & Thermal Systems',
  'Mechanical Engineering w/ Materials Science & Engineering',
  'Mechanical Engineering w/ Mechanics of Materials',
  'Mechanical Engineering w/ Renewable Energy & Environmental Flows',
  'Music',
  'Interdisciplinary Computing & the Arts',
  'Interdisciplinary Computing & the Arts',
  'Music Humanities',
  'Chemical Engineering',
  'NanoEngineering',
  'Philosophy',
  'General Physics',
  'General Physics w/ Secondary Education',
  'Physics',
  'Physics w/ Astrophysics',
  'Biophysics',
  'Physics w/ Computational Physics',
  'Physics w/ Earth Sciences',
  'Physics w/ Materials Physics',
  'Political Science',
  'Political Science - American Politics',
  'Political Science - Comparative Politics',
  'Political Science - International Affairs',
  'Political Science - International Relations',
  'Political Science - Political Theory ',
  'Political Science - Public Law ',
  'Political Science - Public Policy',
  'Political Science - Race, Ethnicity, & Politics',
  'Psychology',
  'Psychology w/ Clinical Psychology',
  'Psychology w/ Cognitive Psychology',
  'Psychology w/ Developmental Psychology',
  'Psychology w/ Human Health',
  'Psychology w/ Sensation & Perception',
  'Psychology w/ Social Psychology',
  'Cognitive & Behavioral Neuroscience ',
  'Business Psychology',
  'Study of Religion',
  'Russian, East European & Eurasian Studies',
  'Geosciences',
  'Marine Biology',
  'Oceanic & Atmospheric Sciences',
  'Sociology - International Studies',
  'Sociology - American Studies',
  'Sociology - Science & Medicine',
  'Sociology - Economy & Society',
  'Sociology - Culture & Communication',
  'Sociology - Social Inequality',
  'Sociology - Law & Society',
  'Structural Engineering',
  'Dance',
  'Theatre',
  'Urban Studies & Planning',
  'Real Estate & Development',
  'Visual Arts - Art History/ Criticism',
  'Visual Arts - Media',
  'Visual Arts - Speculative Design',
  'Visual Arts - Studio',
];
